### ISSUE TITLE
Multiple GPU training problem on slurm !

### ISSUE THREAD

**Issue by Jerrrrykun** [McGill-NLP/topiocqa#10]
Hi, 

I am currently reproducing the training experiment of FiD model. But I met some deadlock problem when I pushed the training job to the slurm. I am using the following sbatch script:

```
#SBATCH --cpus-per-task=32                            # self-explanatory, set to your preference
#SBATCH --ntasks-per-node=1
#SBATCH --mem=40G                                     # self-explanatory, set to your preference
#SBATCH --gres=gpu:8                                 # NOTE: you need a GPU for CUDA support; self-explanatory, set to your preference
#SBATCH --nodes=1

export LD_LIBRARY_PATH=<cuda env>
source activate <conda env>

cd /topiocqa
srun python -m torch.distributed.launch --nproc_per_node=8 \
        FiD/train_reader.py \
        --model_size base \
        --use_checkpoint \
        --lr 0.00005 \
        --optim adamw \
        --scheduler linear \
        --weight_decay 0.01 \
        --text_maxlength 384 \
        --answer_maxlength 100 \
        --per_gpu_batch_size 2 \
        --accumulation_steps 4 \
        --n_context 50 \
        --total_step 15000 \
        --warmup_step 1000 \
        --eval_freq 1000 \
        --checkpoint_dir ./FiD_checkpoint/ \
        --train_data ./downloads/results/retriever/dpr/all_history/train.json \
        --gold_passages_train ./downloads/data/gold_passage_info/all_history/train.json \
        --eval_data ./downloads/results/retriever/dpr/all_history/dev.json

source deactivate
```
(Actually, the above script will call 1 node(--nodes=1) with 8 A100 gpus (--gres=gpu:8). And I also tried to call 8 nodes with 1 A100 gpu per node. But it lead to the deadlock problem as well.)

The error is like:
```
Traceback (most recent call last):
  File "FiD/train_reader.py", line 139, in <module>
    src.slurm.init_distributed_mode(opt)
  File "/topiocqa/FiD/src/slurm.py", line 158, in init_distributed_mode
    torch.distributed.init_process_group(
  File "/condaEnv/xuzhikun-gred/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/condaEnv/xuzhikun-gred/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=1, worker_count=8, timeout=0:30:00)
```

Have you met the same problem when you use the slurm for training?

**Comment by Jerrrrykun** [comment]
Solved with `#SBATCH --mem=200G  `. More memory needed for multiple GPUs.
